DerpQuest: Update Chinese translations
DerpLab/platform_packages_apps_DerpQuest pull request #58
Opened 2020-05-11 11:54 UTC by ALKALiKong233

2020-05-12 22:29 UTC, idoybh approved these changes

2020-05-15 13:47 UTC, idoybh requested changes

2020-05-15 13:47 UTC, idoybh commented on res/values-zh-rCN/derpquest_strings.xml
> +    <string name="category_tiles_title">Tiles area</string>
```suggestion
```
It's literally already defined one line below. Please. Check your file next time. Try to compile with it at least!

2020-05-15 13:48 UTC, idoybh commented on res/values-zh-rCN/derpquest_strings.xml
> +    <string name="category_tiles_title">Tiles area</string>
Please force push to this branch with the requested change. You disallowed me from editing your changes

2020-05-16 01:27 UTC, ALKALiKong233 commented
Finished. Is it OK now?

2020-05-16 03:14 UTC, idoybh approved these changes

2020-05-16 03:14 UTC, merged

2020-05-16 03:18 UTC, idoybh commented
thank you :)